version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-spring-security-demo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: spring_security_demo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
